# Generated by Django 5.1.4 on 2024-12-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='loan_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
