# Generated by Django 5.1.4 on 2024-12-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_alter_approvals_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='area',
            field=models.IntegerField(choices=[(0, 'Rural'), (1, 'Semi-Urban'), (2, 'Urban')], null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='education_status',
            field=models.IntegerField(choices=[(0, 'Graduated'), (1, 'Non_Graduate')], null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='marital_status',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='self_employed',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
    ]
